/**
 * Extension to language name mapping
 * Maps file extensions to their human-readable programming language names
 */
export const EXTENSION_LANGUAGE_MAP: Record<string, string> = {
	astro: "Astro",
	bash: "Bash",
	c: "C",
	cjs: "JavaScript",
	cpp: "C++",
	cs: "C#",
	css: "CSS",
	go: "Go",
	h: "C",
	hpp: "C++",
	html: "HTML",
	java: "Java",
	js: "JavaScript",
	json: "JSON",
	jsx: "JavaScript",
	kt: "Kotlin",
	md: "Markdown",
	mdx: "MDX",
	mjs: "JavaScript",
	php: "PHP",
	py: "Python",
	rb: "Ruby",
	rs: "Rust",
	scss: "SCSS",
	sh: "Shell",
	sql: "SQL",
	svelte: "Svelte",
	swift: "Swift",
	toml: "TOML",
	ts: "TypeScript",
	tsx: "TypeScript",
	vue: "Vue",
	xml: "XML",
	yaml: "YAML",
	yml: "YAML",
};
