import type { Badge, ELogoType, RepositoryInfo } from "../../domain/index";

/**
 * Mermaid diagrams generated by LLM
 */
export interface IMermaidDiagrams {
	architecture?: string;
	dataFlow?: string;
}

/**
 * Data for building the README
 */
export interface IReadmeBuildData {
	acknowledgments?: string;
	badges: Array<Badge>;
	contributing?: string;
	faq: string;
	features: Array<string>;
	highlights?: Array<string>;
	installation: string;
	license: string;
	logoType?: ELogoType;
	logoUrl?: string;
	longDescription: string;
	mermaidDiagrams?: IMermaidDiagrams;
	prerequisites?: Array<string>;
	repositoryInfo: RepositoryInfo;
	roadmap: string;
	shortDescription: string;
	shouldIncludeContributing?: boolean;
	shouldIncludeContributors?: boolean;
	shouldIncludeGithubBadges?: boolean;
	techStack?: Record<string, Array<string>>;
	title: string;
	usage: string;
}

/**
 * Interface for building README content
 */
export interface IReadmeBuilder {
	/**
	 * Build the README content
	 * @param {IReadmeBuildData} data - The data for building the README
	 * @returns {string} The formatted README content
	 */
	build(data: IReadmeBuildData): string;
}
