/**
 * Predefined badge configurations for popular libraries and technologies
 */
export const PREDEFINED_LIB_BADGES: Record<string, { color: string; logo: string; logoColor: string }> = {
	".net": { color: "512BD4", logo: ".net", logoColor: "white" },
	"alpine linux": { color: "0D597F", logo: "alpinelinux", logoColor: "white" },
	android: { color: "3DDC84", logo: "android", logoColor: "white" },
	angular: { color: "DD0031", logo: "angular", logoColor: "white" },
	ansible: { color: "EE0000", logo: "ansible", logoColor: "white" },
	antdesign: { color: "0170FE", logo: "ant-design", logoColor: "white" },
	apache: { color: "D22128", logo: "apache", logoColor: "white" },
	"apollo graphql": { color: "311C87", logo: "apollo-graphql", logoColor: "white" },
	"arch linux": { color: "1793D1", logo: "arch-linux", logoColor: "white" },
	auth0: { color: "EB5424", logo: "auth0", logoColor: "white" },
	aws: { color: "232F3E", logo: "amazonaws", logoColor: "white" },
	axios: { color: "5A29E4", logo: "axios", logoColor: "white" },
	azure: { color: "0078D4", logo: "microsoft-azure", logoColor: "white" },
	babel: { color: "F9DC3E", logo: "babel", logoColor: "black" },
	bitbucket: { color: "0052CC", logo: "bitbucket", logoColor: "white" },
	bootstrap: { color: "7952B3", logo: "bootstrap", logoColor: "white" },
	bun: { color: "000000", logo: "bun", logoColor: "white" },
	"c#": { color: "239120", logo: "csharp", logoColor: "white" },
	"c++": { color: "00599C", logo: "cplusplus", logoColor: "white" },
	docker: { color: "2496ED", logo: "docker", logoColor: "white" },
	eslint: { color: "4B32C3", logo: "eslint", logoColor: "white" },
	express: { color: "000000", logo: "express", logoColor: "white" },
	git: { color: "F05032", logo: "git", logoColor: "white" },
	github: { color: "181717", logo: "github", logoColor: "white" },
	go: { color: "00ADD8", logo: "go", logoColor: "white" },
	javascript: { color: "F7DF1E", logo: "javascript", logoColor: "black" },
	jest: { color: "C21325", logo: "jest", logoColor: "white" },
	kubernetes: { color: "326CE5", logo: "kubernetes", logoColor: "white" },
	mongodb: { color: "47A248", logo: "mongodb", logoColor: "white" },
	mysql: { color: "4479A1", logo: "mysql", logoColor: "white" },
	nestjs: { color: "E0234E", logo: "nestjs", logoColor: "white" },
	"next.js": { color: "000000", logo: "next.js", logoColor: "white" },
	nginx: { color: "009639", logo: "nginx", logoColor: "white" },
	"node.js": { color: "339933", logo: "node.js", logoColor: "white" },
	npm: { color: "CB3837", logo: "npm", logoColor: "white" },
	postgresql: { color: "336791", logo: "postgresql", logoColor: "white" },
	prettier: { color: "F7B93E", logo: "prettier", logoColor: "black" },
	python: { color: "3776AB", logo: "python", logoColor: "white" },
	react: { color: "61DAFB", logo: "react", logoColor: "black" },
	redis: { color: "DC382D", logo: "redis", logoColor: "white" },
	rollup: { color: "EC4A3F", logo: "rollup.js", logoColor: "white" },
	rust: { color: "000000", logo: "rust", logoColor: "white" },
	sass: { color: "CC6699", logo: "sass", logoColor: "white" },
	typescript: { color: "3178C6", logo: "typescript", logoColor: "white" },
	vite: { color: "646CFF", logo: "vite", logoColor: "white" },
	vitest: { color: "6E9F18", logo: "vitest", logoColor: "white" },
	vue: { color: "4FC08D", logo: "vue.js", logoColor: "white" },
	webpack: { color: "8DD6F9", logo: "webpack", logoColor: "black" },
	yarn: { color: "2C8EBB", logo: "yarn", logoColor: "white" },
};
